{
 "title": "camera_1",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "2s" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "<html>\n<head>\n   <style>\n      iframe {\n         display: block;\n         margin: auto;\n      }\n   </style>\n</head>\n<body>\n<iframe src=\"http://localhost:8009/camera_1\" width=\"805\" height=\"475\"></iframe>\n</body>\n</html>"
   }
  },
  {
   "title": "Число машин на участке кругового движения",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influx_1_consumer",
     "query": "SELECT mean(\"cars\") FROM \"camera_1\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "cars_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Загруженность дорог (машин в минуту)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "epm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "influx_1_consumer",
     "query": "SELECT  road_1,\n  road_2,\n  road_3,\n  road_4,\n  road_5 \n FROM \"camera_1\"\nORDER BY time DESC \nLIMIT 1\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "График изменения загруженности дорог",
   "type": "timeseries",
   "description": "число машин в минуту",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 14 },
   "targets": [
    {
     "query": "SELECT  road_1, \n  road_2,\n  road_3,\n  road_4,\n  road_5\nFROM \"camera_1\"\nORDER BY time DESC \n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 24 },
   "options": {
    "content": "<html>\n<head>\n   <style>\n      .container {\n         display: flex;\n         justify-content: center;\n         align-items: center;\n         width: 100%;\n         max-width: 1200px; /* Ограничение максимальной ширины контейнера */\n      }\n      button {\n         background-color: transparent; /* Прозрачный фон */\n         border: 3px solid #4CAF50; /* Зеленая обводка */\n         color: #4CAF50; /* Зеленый текст */\n         padding: 20px 40px; /* Отступы */\n         text-decoration: none; /* Убрать подчеркивание */\n         font-size: 20px; /* Размер шрифта */\n         cursor: pointer; /* Курсор при наведении */\n         border-radius: 16px; /* Закругленные углы */\n         transition-duration: 0.4s; /* Длительность перехода */\n         margin-right: 5px; /* Внешний отступ справа */\n         margin-left: 1px; /* Внешний отступ слева */\n         white-space: nowrap; /* Предотвращение переноса текста */\n      }\n   </style>\n</head>\n<body>\n   <div class=\"container\">\n      <button onclick=\"window.location.href='http://localhost:3111/d/adycu34xs035sb/dashboard-trafficanalyzer-2-camera-influx'\">\n         Перейти на дашборд \"Камера 2\"\n      </button>\n   </div>\n</body>\n</html>"
   }
  }
 ]
}