apiVersion: 1

datasources:
  - name: InfluxDB
    uid: cdycrblq6bf9ce
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: influx
    user: ${INFLUXDB_ADMIN_USER}
    secureJsonData:
      password: ${INFLUXDB_ADMIN_PASSWORD}
    jsonData:
      httpMode: GET
      timeInterval: 1s
    editable: true

  - name: PostgreSQL
    uid: f848db3d-2635-4913-be1c-ae2d0db7c90a
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    database: traffic_platform
    user: traffic
    secureJsonData:
      password: traffic123
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    editable: true
